services:
  - type: web
    name: gopredict-backend
    env: python
    rootDir: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start_api.py --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: $PORT
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
